spring:
  redis:
    host: 192.168.56.10
    port: 6379
    password:
    database: 0
#  rabbitmq:
#    host: 192.168.56.10
#    username: root
#    password: root
#    port: 5672
#    virtual-host: demo_host
  jedis:
    pool:
      max-active: 200
      min-idle: 20
      max-wait: 3000ms
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimail_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration-properties:


